### ISSUE TITLE
When i do a demo_pose_estimation.ipynb,there is a mistake

### ISSUE THREAD

**Issue by chrispolo** [Superlee506/Mask_RCNN#10]
Hello, @Superlee506 i come here again,i will post the code and the mistake,i hope you can  help me solve this problem.i want to upload the code in a txt but it made a mistake so i copy the code here and # **the  coding result is like this:**
Processing 1 images
image                    shape: (375, 500, 3)         min:    0.00000  max:  255.00000
molded_images            shape: (1, 256, 256, 3)      min: -123.70000  max:  143.10000
image_metas              shape: (1, 10)               min:    0.00000  max:  500.00000
windows                  shape: (1, 4)                min:    0.00000  max:  256.00000
rpn_class                shape: (1, 16368, 2)         min:    0.00000  max:    1.00000
rpn_bbox                 shape: (1, 16368, 4)         min:  -12.89529  max:   49.82267
rois                     shape: (1, 1000, 4)          min:    0.00000  max:    1.00000
mrcnn_class              shape: (1, 1000, 2)          min:    0.00846  max:    0.99154
mrcnn_bbox               shape: (1, 1000, 2, 4)       min:   -2.42059  max:    2.88191
detections               shape: (1, 100, 6)           min:    0.00000  max:  256.00000
mrcnn_mask               shape: (1, 100, 28, 28, 2)   min:    0.10440  max:    0.90474
mrcnn_keypoint_prob      shape: (1, 100, 17, 3136)    min:    0.00000  max:    0.02576

IndexError                                Traceback (most recent call last)
<ipython-input-28-b488b5435f82> in <module>()
      6 results = model.detect_keypoint([image], verbose=1)
      7 r = results[0]
----> 8 visualize.display_keypoints(image,r['rois'], r['class_ids'], r['scores'],r['keypoints'],r['masks'])

~/Downloads/Mask_RCNN_Humanpose-master/visualize.py in display_keypoints(image, boxes, keypoints, class_ids, class_names, skeleton, scores, title, figsize, ax)
    330         class_id = class_ids[i]
    331         score = scores[i] if scores is not None else None
--> 332         label = class_names[class_id]
    333         x = random.randint(x1, (x1 + x2) // 2)
    334         caption = "{} {:.3f}".format(label, score) if score else label

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
**# code:**
`import os
import sys
import random
import math
import numpy as np
import skimage.io
import matplotlib
import matplotlib.pyplot as plt

import coco
import utils
import model as modellib
import visualize
from model import log

%matplotlib inline 

# Root directory of the project
ROOT_DIR = os.getcwd()

# Directory to save logs and trained model
MODEL_DIR = os.path.join(ROOT_DIR, "logs")

# Local path to trained weights file
COCO_MODEL_PATH = os.path.join(ROOT_DIR, "mask_rcnn_coco_humanpose.h5")
# Download COCO trained weights from Releases if needed
if not os.path.exists(COCO_MODEL_PATH):
    utils.download_trained_weights(COCO_MODEL_PATH)

IMAGE_DIR = os.path.join(ROOT_DIR, "images")

class InferenceConfig(coco.CocoConfig):
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1
    USE_MINI_MASK = True
    IMAGE_MIN_DIM = 256
    IMAGE_MAX_DIM = 256

config = InferenceConfig()

# Recreate the model in inference mode
model = modellib.MaskRCNN(mode="inference", 
                          config=config,
                          model_dir=MODEL_DIR)

# Get path to saved weights
# Either set a specific path or find last trained weights
model_path = COCO_MODEL_PATH
# Load trained weights (fill in path to trained weights here)
assert model_path != "", "Provide path to trained weights"
print("Loading weights from ", model_path)
model.load_weights(model_path, by_name=True,exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", 
                                "mrcnn_bbox", "mrcnn_mask"])

# Load a random image from the images folder
file_names = next(os.walk(IMAGE_DIR))[2]
image = skimage.io.imread(os.path.join(IMAGE_DIR, random.choice(file_names)))

# Run detection
results = model.detect_keypoint([image], verbose=1)
r = results[0]
visualize.display_keypoints(image,r['rois'], r['class_ids'], r['scores'],r['keypoints'],r['masks'])`
I am very glad to hear from you about this problem
Thx a lot!

**Comment by Superlee506** [comment]
@chrispolo I think you you make a mistake in "visualize.display_keypoints(image,r['rois'], r['class_ids'], r['scores'],r['keypoints'],r['masks'])".
It should be:
visualize.display_keypoints(original_image,r['rois'],r['keypoints'],r['class_ids'],val_dataset_keypoints.class_names)

**Comment by chrispolo** [comment]
@Superlee506  Thanks for your reply,when i changed like yours ,it showed the "original_image ""val_dataset_keypoint.class_names" is not defined.  Your inference_humanpsoe.ipynb and inspect_humanpose.ipynb are all  random choice a image from the val2017 or train2017.But how can i choice a image from others  to test the humanpose like the demo.ipynb designed by the **https://github.com/matterport/Mask_RCNN/blob/master/samples/demo.ipynb** 
Thx a lot  !

**Comment by Superlee506** [comment]
@chrispolo  You can use ["BG", "person"] instead of ""val_dataset_keypoint.class_names".

**Comment by chrispolo** [comment]
when i change like this 
# Load a random image from the images folder
file_names = next(os.walk(IMAGE_DIR))[2]
original_image = skimage.io.imread(os.path.join(IMAGE_DIR, random.choice(file_names)))
results = model.detect_keypoint([original_image], verbose=0)
r = results[0]
visualize.display_keypoints(original_image,r['rois'],r['keypoints'],r['class_ids'],["BG", "person"])
 **the results is:**
![image](https://user-images.githubusercontent.com/37335192/38594457-ea2646e0-3d78-11e8-92a9-95c691c72d85.png)
![image](https://user-images.githubusercontent.com/37335192/38594497-1d2674fc-3d79-11e8-8fa3-ab761a54d4df.png)

**Comment by Superlee506** [comment]
@chrispolo You can refers to my new demo for[ image input ](https://github.com/Superlee506/Mask_RCNN_Humanpose/blob/master/demo_human_pose.ipynb)
and new demo for [camera input](https://github.com/Superlee506/Mask_RCNN_Humanpose/blob/master/video_demo.py).

**Comment by chrispolo** [comment]
Thx for your patient answer!!! @Superlee506
