### ISSUE TITLE
Maybe I found the solution to the issues:the Model cannot distinguish between left knee and right  knee

### ISSUE THREAD

**Issue by huaifeng1993** [Superlee506/Mask_RCNN#11]
there are two funcions in utils.py get_keypoints() and flip_keypoints() which are used in model.py to augment data.i just set the the paramer 'argument ' of the function load_image_gt_keypoints() and other functions refering the  load_image_gt_keypoints()  to 'Flase',and this issue was sovled.
```

**Comment by Superlee506** [comment]
@huaifeng1993 You set the value to False and train the model again?

**Comment by huaifeng1993** [comment]
@Superlee506 the 8/5000
the issue  you Mentioned haunted me also before I set the value to False ,but I train the model on another data not coco that why i said "maybe ".by the way, are you chinese?说英语略累。。。

**Comment by Superlee506** [comment]
@huaifeng1993 哈哈，我是中国人，只是在美国念书而已。我觉得，关掉Keypoint的数据增强并不能解决左右区分的问题，因为在测试的时候，数据增强是关掉的。

**Comment by huaifeng1993** [comment]
@Superlee506 哈哈 大佬哇，非常感谢大佬的代码，数据增强开和关，我分别训练过，因为之前训练的一个model只有4个点，我把数据增强关掉，效果确实有所提升。目前正在训练更多的点的模型，如果有所改善，我再回来确认一下。

**Comment by huaifeng1993** [comment]
我在训练的时候就关掉了。

**Comment by huaifeng1993** [comment]
@Superlee506 在我的训练集上，左右不分的情况确实减少了了，检查了一部分图片，没有看到左右不分的情况，之前这种情况普遍存在。如果有时间可以尝试一下，在训练的时候就把参数设为False.

**Comment by Superlee506** [comment]
@huaifeng1993 感谢建议，之前我试过将左右翻转关掉然后训练，但是在coco的数据集上还是会出现左右不分的情况~可能你的数据的场景比COCO的简单一些。我参考了Openpose等网络，他们在初期也会出现左右不分的情况，多个网络层进行迭代可能是解决这个问题的根本手段

**Comment by huaifeng1993** [comment]
谢谢指教，我数据场景确实简单，我也才涉及深度，这方面的工作认识不深。

**Comment by filipetrocadoferreira** [comment]
Sorry, any conclusions on this topic?

**Comment by Superlee506** [comment]
@filipetrocadoferreira The difficulty in distinguishing left/right keypoints maybe not caused by the  flip_keypoints method and I'm sure about it's correctness . As I refer to Openpose model, I find that in some early states, their model can't distinguish these symmetrical keypoints, and maybe the iterative stages could finally solve this.
