### ISSUE TITLE
How to connect the keypoint of the human pose together like the openpose in maskrcnn?

### ISSUE THREAD

**Issue by chrispolo** [Superlee506/Mask_RCNN#12]
Thanks  for your job   and your former guidance and after i learned your project and code, i want to ask a question about  when you got the keypoint of human pose.How to connect the
Thx so much!!
![screenshot from 2018-04-16 20-04-39](https://user-images.githubusercontent.com/37335192/38808162-ba17ccde-41b1-11e8-97c2-70f8fc374759.png)

**Comment by chrispolo** [comment]
Thanks for your job and your former guidance and after i learned your project and code, i want to ask a question about when you got the keypoint of human pose.How to connect the keypoint?
Thx so much!!

**Comment by chrispolo** [comment]
Thanks for your job and your former guidance and after i learned your project and code, i want to ask a question about when you got the keypoint of human pose.How to connect the keypiont like the openpose?
Thx so much!!

**Comment by Superlee506** [comment]
@chrispolo It's simple to do this, you can define some connections between these keypoints and draw some line using cv2.Line. If I'm not busy I will update the code.

**Comment by chrispolo** [comment]
@Superlee506 Thanks for your answer, i  am just a new beginner and try to learn  the code, hope you will update the code  in your convenience.

**Comment by Superlee506** [comment]
@chrispolo I have updated some codes for visualizing the connection please check it.
