### ISSUE TITLE
Different Configs in Training/Inference

### ISSUE THREAD

**Issue by filipetrocadoferreira** [Superlee506/Mask_RCNN#14]
I just checked that your configuration in inference 

```
# Load dataset
class InferenceConfig(coco.CocoConfig):
    GPU_COUNT = 1
    IMAGES_PER_GPU = 4
    KEYPOINT_MASK_POOL_SIZE = 17
```

is different than in training:

`KEYPOINT_MASK_POOL_SIZE = 7`

If in inference you put `KEYPOINT_MASK_POOL_SIZE = 7` results are better and faster (!!!)

**Comment by Superlee506** [comment]
@filipetrocadoferreira It's true. Sorry for my mistake. I mistake the "KEYPOINT_MASK_POOL_SIZE " as "KEYPOINT_NUM".  Thank you so much, this problem confused me for such a long time. I will update the code soon. I think our accuracy will be closer to the original paper. Thanks again.
