### ISSUE TITLE
How to train a new model without the pre-trained COCOweight?

### ISSUE THREAD

**Issue by chrispolo** [Superlee506/Mask_RCNN#15]
Hello @Superlee506 , i came back again, Your train_human_pose.ipynb shows how to train a model about the humanpose,but i want to train a new model about humanpose  without the pre_trained"mask_rcnn_coco.h5", How should i change?  and if i trained with pretrained weight,the model i got will be based on the pre-trained weight?
Thx a lot,hope you give  me a answer in your convenience.

**Comment by Superlee506** [comment]
@chrispolo If you don't want to initial the model with pre-trained model, you just need to uncomment the "model.load_weights". If you trained with pretrained weight, the model just initial the weight using this pretrained model.
