### ISSUE TITLE
The structure of keypoint head

### ISSUE THREAD

**Issue by Emrys-Lee** [Superlee506/Mask_RCNN#16]
Hi, I want to discuss the structure of keypoint head network a little bit.

According to Fig 4 right in the original paper, the size of ROI pooling should be 14, so the following eight convolutions should be done on 14 * 14 inputs, not 7 * 7.
Additionally, the author says

> followed by a deconv layer and 2x bilinear upscaling. 

From my understanding, there is only one bilinear layer. "2x" is the change of shape, not the number of bilinear layers.

What do you think?

**Comment by Superlee506** [comment]
@Emrys-Lee Thanks for your suggestion, you are right. I will update my code and model  then. Thanks.

**Comment by Emrys-Lee** [comment]
You are welcome. Hope that will help to increase the accuracy to some extent.
