### ISSUE TITLE
Could keypoints be used to detect features such as corners of an object?

### ISSUE THREAD

**Issue by fastlater** [Superlee506/Mask_RCNN#2]
I would like to know if this algorithm could be used for corner detection if enough data about what is a corner is provided. I guess that if this algorithm can find body parts in an image no matter where it is, it should be possible to detect a simple feature as a corner of a simple shape such as a rectangle, triangle, polygon, etc.
  
I have been reading 2 papers presented by the same author:
https://arxiv.org/abs/1707.07410
https://arxiv.org/abs/1712.07629
I still asking myself how alike mask rcnn is compared to MagicPoint network. Do you think keypoint detection using your keypoint mask rcnn could outputs results similar to the network presented in those papers where a Encoder-Decoder Network outputs a heatmap of corner-ness?

**Comment by Superlee506** [comment]
@fastlater I think it's the same problem with keypoint detection. In keypoint detection, some other methods also use heatmap as the output.

**Comment by fastlater** [comment]
@Superlee506  Thank you for your feedback. Just as a conclusion, if I train the algorithm with thousands/millions of corners from rectangles and polygons, after training, it will be capable of detecting corners of a different shape such as a triangle?

**Comment by Superlee506** [comment]
@fastlater You can do some experiments to check it.

**Comment by fastlater** [comment]
Ok. Thanks. I will try.
