### ISSUE TITLE
how to train my own dataset

### ISSUE THREAD

**Issue by zxczhkzxc** [Superlee506/Mask_RCNN#20]
hello, i want to use this probject to train my own dataset,what tools can i use to 
mark my dataset? via? or others? the second problem is what i marked my dataset, whether i should convert it to some format?

**Comment by Superlee506** [comment]
@zxczhkzxc Hi, sorry for my late reply. You can use [Label me](http://labelme.csail.mit.edu/Release3.0/) to annotate your own datas, and refers to https://github.com/Superlee506/Mask_RCNN_Humanpose/blob/master/coco.py to prepare your dataset.
