### ISSUE TITLE
Detect all classes from Matterport

### ISSUE THREAD

**Issue by kyamz** [Superlee506/Mask_RCNN#22]
What steps are required to get visualize.display_instances() working with all the classes from Matterport? I'd like to be able to detect human pose but also all the other classes besides people.

**Comment by Superlee506** [comment]
Hi, sorry for my late reply. I'm busy with my  doctoral dissertation these months. You can refer to the official demo https://github.com/matterport/Mask_RCNN/blob/master/samples/demo.ipynb
