### ISSUE TITLE
What is LIMBS?

### ISSUE THREAD

**Issue by chenzhaiyu** [Superlee506/Mask_RCNN#27]
Hello,

I'm currently adapting your project to detecting buildings from aerial imagery with corners as keypoints. I see in the revised CocoConfig class there is a LIMBS list as

> LIMBS = [0,-1,-1,5,-1,6,5,7,6,8,7,9,8,10,11,13,12,14,13,15,14,16]

Could you explain a bit what's the meaning of this LIMBS list?

Thanks.

**Comment by Superlee506** [comment]
Hi, LIMBS stands for the start_index and right_index of every limb, you can resize it to [11, 2]. If some keypoints are not belong to any limb then one of the points will be -1. You can refers to [#L356](https://github.com/Superlee506/Mask_RCNN_Humanpose/blob/master/visualize.py#L356)
