### ISSUE TITLE
Train my own dataset

### ISSUE THREAD

**Issue by hx121071** [Superlee506/Mask_RCNN#28]
I train my own datasets, the keypoints number is 19, the start keypoints loss is 8.05, the keypoints loss  converges to 3.0 after 100 epochs training with "heads", when I train "4+" or "all", the keypoints loss won't decrease too much, and the keypoints loss will be around 2.8. I want to known, your coco humanpose keypoints loss  will converge to what value? Thank you.

**Comment by Superlee506** [comment]
@hx121071 Have you visualized the final results? I remember my final loss could converge to near 0.x .

**Comment by hx121071** [comment]
我可视化了结果，结果泛化性能不是太好，我自己的数据集是没有mask的，因此我只使用了keypoint_mrcnn_mask_loss，把代码中有关mrcnn_mask的去掉了，应该没影响吧？

**Comment by Superlee506** [comment]
@hx121071 这个关系不大的，建议检查一下训练的代码。如果训练数据无误的话，基本上训练几个epoch效果就不错了，除了对称点难以区分之外，对称点的问题，可以参考http://blog.dlib.net/2018/01/correctly-mirroring-datasets.html
