### ISSUE TITLE
keypoint mask loss

### ISSUE THREAD

**Issue by ghost** [Superlee506/Mask_RCNN#29]
"If you still want to use the keypoint mask as output, you'd better adopt the modified loss function proposed by @QtSignalProcessing in issue#2. Because after crop and resize, the keypoint masks may have more than one 1 values, and this will make the original soft_cross entropy_loss hard to converge."

can you please guide me how to do the modifications? is the current loss implemented by you is the same as described in the paper?

**Comment by Superlee506** [comment]
@adarvit Yes, the suggestion above is from my comment. My implementation is the same with the paper.
