### ISSUE TITLE
when I run inference_humanose.ipynb, the error  is "from pycocotools import mask as maskUtils  ImportError: No module named 'pycocotools'"?

### ISSUE THREAD

**Issue by hdjsjyl** [Superlee506/Mask_RCNN#3]
Hi, thanks for your code. It is very nice. I meet a problem, when I run inference_humanpose.ipynb:
and I do not find the file pycocotools, any advice will be appreciated. Thank you very much.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-d9e1af0f3aa1> in <module>()
      8 import matplotlib.pyplot as plt
      9 
---> 10 import coco
     11 import utils
     12 import model as modellib

~/Downloads/Mask_RCNN_Humanpose-master/coco.py in <module>()
     38 # If the PR is merged then use the original repo.
     39 # Note: Edit PythonAPI/Makefile and replace "python" with "python3".
---> 40 from pycocotools.coco import COCO
     41 from pycocotools.cocoeval import COCOeval
     42 from pycocotools import mask as maskUtils

ImportError: No module named 'pycocotools'

**Comment by Superlee506** [comment]
@hdjsjyl Hi, thanks for your interest, you can download the pretrained model here: https://github.com/Superlee506/Mask_RCNN_Humanpose/releases

**Comment by hdjsjyl** [comment]
@Superlee506 , thanks for your reply. I solved this problem. Actually, I want to fit human pose estimation part to facial landmarks. Do you think it is reasonable? Can you give me some advice? Any advice will be appreciated. Thanks

**Comment by Superlee506** [comment]
@hdjsjyl For facial landmarks detection,  you should firstly change the bbox head for face detecation rather than human detection. Secondly, change the keypoint head for face.

**Comment by hdjsjyl** [comment]
@Superlee506 , thanks for your advice. I will read your code line by line. Thank you very much.

**Comment by hdjsjyl** [comment]
@Superlee506 ,  Now I have changed segmentation part for keypoint detection. But I found that rcnnL1Loss will be very big such as 234677418896143419441152.0000 from beginning. Do you know what is the reason? Any advice will be appreciated. Thank you.

**Comment by Superlee506** [comment]
@hdjsjyl pycocotools is a third-party package for operating the coco dataset. You can install it as described in https://github.com/cocodataset/cocoapi
