### ISSUE TITLE
Code running problem

### ISSUE THREAD

**Issue by bskim3296** [Superlee506/Mask_RCNN#6]
I'm trying to run your code in Windows 10 (tensorflow 1.6.0, CUDA 9.0, CuDNN 7.1.2) environment.
When I run inference_humanpose,  I got error same as below figure.
![error](https://user-images.githubusercontent.com/20894969/38290482-5c5826c4-3816-11e8-8d35-fdcc6d5eb627.png)
How can I fix it?    I'm beginner on Deep Learning.

**Comment by JichenGuo** [comment]
Hi,
have you successfully run it in Windows?
