### ISSUE TITLE
can't find person_keypoints_train2017.json

### ISSUE THREAD

**Issue by chrispolo** [Superlee506/Mask_RCNN#7]
Firstly,i want to thanks for your job,but when i run your code,when i load the dataset,which showed [Errno 2] No such file or directory: 'images/annotations/person_keypoints_train2017.json'
So can you  provided it?
Thx a lot

**Comment by wuhuhu800** [comment]
I have encountered the same problem.

**Comment by Superlee506** [comment]
@chrispolo @wuhuhu800 You need to download the coco dataset http://cocodataset.org/#download
