### ISSUE TITLE
Results error in 'inference_humanpose.ipynb'

### ISSUE THREAD

**Issue by bskim3296** [Superlee506/Mask_RCNN#8]
Hello, thank you for your project.

I got error on  'inference_humanpose.ipynb' code.

When I tests on a random image, code running well
But I test for one image, I got error as below picture
![1](https://user-images.githubusercontent.com/20894969/38488340-200ee642-3c1e-11e8-95de-f1ef8964c207.png)
![2](https://user-images.githubusercontent.com/20894969/38488341-215fb5bc-3c1e-11e8-9a8e-86480d10b56b.png)

I just change COCO_DIR path in your code.
I don't know what the problem is. Thank u for help :)

**Comment by Superlee506** [comment]
@bskim3296  You can post your changed code here. I think you must ignore something. The detection would be right.
